---
- hosts: centos
  gather_facts: true

  tasks:
  - name: Check RAM usage
    command: free -m
    register: ram_usage

  - debug: var=ram_usage.stdout_lines

  - name:  Check disk usage
    command: df -hT
    register: disk_usage

  - debug: var=disk_usage.stdout_lines

  - name: Check Virtual memory usage
    command: vmstat
    register: vm_usage

  - debug: var=vm_usage.stdout_lines

