---
- hosts: centos
  gather_facts: true
  become: true

  tasks:
  - name: Install multiple packages
    yum: 
      name: "{{ item }}" 
      state: latest
    with_items: 
    -  "wget" 
    -  "git"
    -  "docker"

- hosts: centos
  gather_facts: true
  become: true
  
  tasks:
  - name : Install python2 
    yum:   
       name: python2
       state: latest

