---
# tasks file for httpd

  - name: Install httpd
    yum:
      name: httpd
      state: latest
  
  - name: Start httpd service
    service:
        name: httpd
        state: started

  - name: Disable the pre-set welcome page
    shell: "sed -i 's/^/&#/g' {{ welcome_page }} "



  - name: Copy welcome page
    template: 
      src : ./index.html
      dest: /var/www/html 
    notify: Restart Apache 













